import * as OTPAuth from "otpauth";

/**
 * Admin TOTP second factor (ADR-007/010). The secret is stored as
 * `AdminUser.totpSecretEnc` (AES-256-GCM via lib/crypto) and decrypted only in
 * the login path. Standard RFC-6238: SHA-1, 6 digits, 30s period — the values
 * every authenticator app (Google Authenticator, Authy, 1Password) assumes.
 */
const ISSUER = "U-Rest";
const PERIOD = 30;
const DIGITS = 6;
const ALGORITHM = "SHA1";
const WINDOW = 1; // ±1 step (~30s) clock-skew tolerance

function totp(secret: string, label = "admin"): OTPAuth.TOTP {
  return new OTPAuth.TOTP({
    issuer: ISSUER,
    label,
    algorithm: ALGORITHM,
    digits: DIGITS,
    period: PERIOD,
    secret: OTPAuth.Secret.fromBase32(secret),
  });
}

/** New random base32 secret (160-bit) — generated by the management script. */
export function generateTotpSecret(): string {
  return new OTPAuth.Secret({ size: 20 }).base32;
}

/** Generate the current token (used by tests and enrollment self-check). */
export function generateToken(secret: string, timestamp?: number): string {
  return totp(secret).generate({ timestamp });
}

export function verifyTotp(
  secret: string,
  token: string,
  timestamp?: number,
): boolean {
  return totp(secret).validate({ token, timestamp, window: WINDOW }) !== null;
}

/** `otpauth://` URI for authenticator enrollment (printed by the mgmt script). */
export function totpAuthUri(secret: string, accountEmail: string): string {
  return totp(secret, accountEmail).toString();
}
